### NumPy Exercises for Data Analysis

In [1]:
import numpy as np

#### 1. Create a 1D array of numbers from 0 to 9

In [10]:
dataset = np.arange(0,10)

In [11]:
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


#### 2. Create a 3×3 numpy array of all True’s

In [21]:
dataset_1 = np.full((5, 5), True, dtype=bool)

In [22]:
print(dataset_1)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


#### 3. Extract all odd numbers from arr

In [41]:
dataset_2 = np.arange(0,10)
dataset_2[dataset_2 % 2 == 1]

array([1, 3, 5, 7, 9])

#### 4. Replace all odd numbers in arr with -1

In [43]:
dataset_2[dataset_2 % 2 == 1] =-1
print(dataset_2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 5. Replace all odd numbers in arr with -1 without changing 

In [99]:
dataset_3 = np.arange(10)

In [100]:
dataset_4 = np.where(dataset_3 % 2 == 1, -1, dataset_3)

In [101]:
print(f"input data: {dataset_3} \nnew data: {dataset_4}")

input data: [0 1 2 3 4 5 6 7 8 9] 
new data: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 6. Convert a 1D array to a 2D array with 2 rows

In [106]:
dataset_5 = np.arange(10)


In [112]:
dataset_5.reshape((2, 5)) # reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 7. Stack arrays a and b vertically

In [113]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [120]:
print(f"{a},\n{b}")

[[0 1 2 3 4]
 [5 6 7 8 9]],
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [129]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [130]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [131]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])