### NumPy Exercises for Data Analysis

In [1]:
import numpy as np

#### 1. Create a 1D array of numbers from 0 to 9

In [10]:
dataset = np.arange(0,10)

In [11]:
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


#### 2. Create a 3×3 numpy array of all True’s

In [21]:
dataset_1 = np.full((5, 5), True, dtype=bool)

In [22]:
print(dataset_1)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


#### 3. Extract all odd numbers from arr

In [41]:
dataset_2 = np.arange(0,10)
dataset_2[dataset_2 % 2 == 1]

array([1, 3, 5, 7, 9])

#### 4. Replace all odd numbers in arr with -1

In [43]:
dataset_2[dataset_2 % 2 == 1] =-1
print(dataset_2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 5. Replace all odd numbers in arr with -1 without changing 

In [99]:
dataset_3 = np.arange(10)

In [100]:
dataset_4 = np.where(dataset_3 % 2 == 1, -1, dataset_3)

In [101]:
print(f"input data: {dataset_3} \nnew data: {dataset_4}")

input data: [0 1 2 3 4 5 6 7 8 9] 
new data: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 6. Convert a 1D array to a 2D array with 2 rows

In [106]:
dataset_5 = np.arange(10)


In [112]:
dataset_5.reshape((2, 5)) # reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 7. Stack arrays a and b vertically

In [113]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [120]:
print(f"{a},\n{b}")

[[0 1 2 3 4]
 [5 6 7 8 9]],
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [129]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [130]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [131]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 8. Stack the arrays a and b horizontally

In [132]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [133]:
print(f"{a}\n{b}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [138]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [139]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### 9. Create the following pattern without hardcoding.

In [141]:
a = np.array([1,2,3])

In [142]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [143]:
np.repeat(a, 3), np.tile(a, 3)

(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3]))

#### 10. Get the common items between a and b

In [144]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [145]:
np.intersect1d(a, b)

array([2, 4])

#### 11. From array a remove all items present in array b

In [166]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [168]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

#### 12. Get the positions where elements of a and b match

In [173]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [176]:
np.where(a == b)

(array([1, 3, 5, 7]),)

#### 13. Get all items between 5 and 10 from a

In [177]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [195]:
out = np.where((a >= 5)&(a <=10))
a[out]

array([ 6,  9, 10])

In [196]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

#### 14. Convert the function maxx that works on two scalars, to work on two arrays

In [200]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [197]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [203]:
pair_max = np.vectorize(maxx, otypes=[float])

In [204]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

#### 15. Swap columns 1 and 2 in the array arr

In [206]:
arr = np.arange(9).reshape(3,3)

In [207]:
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
arr[:, [2, 0]] = arr[:, [0, 2]]

In [209]:
arr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [210]:
arr[[1,0,2], :]

array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])